apiVersion: v1
kind: Service
metadata:
  name: actix-web-app-service
  namespace: actix-web-app
spec:
  selector:
    app: actix-web-app
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
  type: LoadBalancer # Change to NodePort if running on a local cluster